name: ds2-coiled-2025-binder
channels:
  - conda-forge
dependencies:
#  - pangeo-notebook==2024.02.02
  - python = 3.11.7
  - xarray = 2024.1.1
  - hvplot = 0.9.1
  - gcsfs = 2023.12.2.post1
  - intake = 0.7.0
  - intake-xarray = 0.7.0
  - zarr = 2.16.1
  - cartopy = 0.22.0
  - scikit-learn = 1.4.0
  - seaborn = 0.13.2
  - dask-ml = 2023.3.24
  - coiled = 1.71.1
  - google-cloud-sdk = 502.0.0
  - ipykernel = 6.29.0
  - argopy = 0.1.14
  - s3fs = 2023.12.2
  - xarrayutils = 2.0.0
  - copernicusmarine = 1.3.5

  - cloudpickle = 3.0.0
  - dask = 2024.1.1
  - distributed = 2024.1.1
  - numpy = 1.26.3
  - pandas = 2.2.0
  - toolz = 0.12.1
  - tornado = 6.3.3

  - pip = 24.3.1
  - pip:
    - httpimport==1.4.0
    - coiled[notebook]
    - pyopenssl==24.3.0
    - msgpack==1.0.7
