name: ds2-coiled-2025
channels:
  - conda-forge
dependencies:
  - python = 3.11
  - xarray = 2024.10.0
  - hvplot = 0.11.1
  - gcsfs = 2024.10.0
  - intake = 2.0.7
  - intake-xarray = 0.7.0
  - zarr = 2.18.3
  - cartopy = 0.24.0
  - scikit-learn = 1.6.0
  - seaborn = 0.13.2
  - dask-ml = 2024.4.4
  - coiled = 1.67.0
  - google-cloud-sdk = 502.0.0
  - ipykernel = 6.29.5
  - argopy = 1.0.0
  - s3fs = 2024.10.0
  - xarrayutils = 2.0.1
  - copernicusmarine = 1.3.5
  - pip = 24.3.1
  - pip:
    - httpimport==1.4.0
    - coiled[notebook]
    - pyopenssl==24.3.0
