FROM pangeo/pangeo-notebook:2024.02.02
# We recommend using a specific tag above from https://hub.docker.com/r/pangeo/pangeo-notebook/tags
RUN pip install --no-cache-dir coiled "coiled[notebook]" "dask[complete]"
