name: tests environments

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  build:
    # CI tests for environments with core requirements in pinned versions
    # All commits must pass this

    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      max-parallel: 12
      fail-fast: false
      matrix:
        python-version: ["3.11"]
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        experimental: [false]

    steps:
      - uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          echo "CONDA_ENV_FILE=practice/environment/environment-coiled-pinned-binder.yml" >> $GITHUB_ENV
          echo "PYTHON_VERSION=${{ matrix.python-version }}" >> $GITHUB_ENV
          echo "LOG_FILE=Py${{matrix.python-version}}-${{matrix.os}}.log" >> $GITHUB_ENV

      - name: Setup Micromamba ${{ matrix.python-version }}
        uses: mamba-org/setup-micromamba@v2
        with:
          micromamba-version: '1.5.10-0'
          environment-name: ds2-tests
          environment-file: ${{ env.CONDA_ENV_FILE }}
          init-shell: bash
          cache-environment: true
          cache-environment-key: "${{runner.os}}-${{runner.arch}}-py${{matrix.python-version}}-${{env.TODAY}}-${{hashFiles(env.CONDA_ENV_FILE)}}"
          create-args: >-
            python=${{matrix.python-version}}

      - name: Version info
        run: |
          micromamba info
          micromamba list > $LOG_FILE

      - name: Save tests log as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Build-${{matrix.python-version}}-${{matrix.os}}
          path: ${{env.LOG_FILE}}
          retention-days: 90
