name: tests environments

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
#  build-ubuntu:
#
#    name: ${{ matrix.os }}
#    runs-on: ${{ matrix.os }}
#    defaults:
#      run:
#        shell: bash -l {0}
#    continue-on-error: ${{ matrix.experimental }}
#    strategy:
#      max-parallel: 12
#      fail-fast: false
#      matrix:
#        python-version: ["3.11"]
#        os: ["ubuntu-latest"]
#        experimental: [false]
#
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Set environment variables
#        run: |
#          echo "CONDA_ENV_FILE=practice/environment/coiled/environment-coiled-pinned-binder.yml" >> $GITHUB_ENV
#          echo "PYTHON_VERSION=${{ matrix.python-version }}" >> $GITHUB_ENV
#          echo "LOG_FILE=Py${{matrix.python-version}}-${{matrix.os}}.log" >> $GITHUB_ENV
#
#      - name: Setup Micromamba ${{ matrix.python-version }}
#        uses: mamba-org/setup-micromamba@v2
#        with:
#          micromamba-version: '1.5.10-0'
#          environment-name: ds2-tests
#          environment-file: ${{ env.CONDA_ENV_FILE }}
#          init-shell: bash
#          cache-environment: true
#          cache-environment-key: "${{runner.os}}-${{runner.arch}}-py${{matrix.python-version}}-${{env.TODAY}}-${{hashFiles(env.CONDA_ENV_FILE)}}"
#          create-args: >-
#            python=${{matrix.python-version}}
#
#      - name: Version info
#        run: |
#          micromamba info
#          micromamba list > $LOG_FILE
#
#      - name: Save tests log as artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: Build-${{matrix.python-version}}-${{matrix.os}}
#          path: ${{env.LOG_FILE}}
#          retention-days: 90
#
#  build-macos:
#
#    name: ${{ matrix.os }}
#    runs-on: ${{ matrix.os }}
#    defaults:
#      run:
#        shell: bash -l {0}
#    continue-on-error: ${{ matrix.experimental }}
#    strategy:
#      max-parallel: 12
#      fail-fast: false
#      matrix:
#        python-version: ["3.11"]
#        os: ["macos-latest"]
#        experimental: [false]
#
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Set environment variables
#        run: |
#          echo "CONDA_ENV_FILE=practice/environment/coiled/environment-coiled-pinned-binder.yml" >> $GITHUB_ENV
#          echo "PYTHON_VERSION=${{ matrix.python-version }}" >> $GITHUB_ENV
#          echo "LOG_FILE=Py${{matrix.python-version}}-${{matrix.os}}.log" >> $GITHUB_ENV
#
#      - name: Setup Micromamba ${{ matrix.python-version }}
#        uses: mamba-org/setup-micromamba@v2
#        with:
#          micromamba-version: '1.5.10-0'
#          environment-name: ds2-tests
#          environment-file: ${{ env.CONDA_ENV_FILE }}
#          init-shell: bash
#          cache-environment: true
#          cache-environment-key: "${{runner.os}}-${{runner.arch}}-py${{matrix.python-version}}-${{env.TODAY}}-${{hashFiles(env.CONDA_ENV_FILE)}}"
#          create-args: >-
#            python=${{matrix.python-version}}
#
#      - name: Version info
#        run: |
#          micromamba info
#          micromamba list > $LOG_FILE
#
#      - name: Save tests log as artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: Build-${{matrix.python-version}}-${{matrix.os}}
#          path: ${{env.LOG_FILE}}
#          retention-days: 90

  build-windows:

    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      max-parallel: 12
      fail-fast: false
      matrix:
        python-version: ["3.11"]
        os: ["windows-latest"]
        experimental: [false]

    steps:
      - uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          echo "CONDA_ENV_FILE=practice/environment/coiled/environment-coiled-pinned-binder-windows.yml" >> $GITHUB_ENV
          echo "PYTHON_VERSION=${{ matrix.python-version }}" >> $GITHUB_ENV
          echo "LOG_FILE=Py${{matrix.python-version}}-${{matrix.os}}.log" >> $GITHUB_ENV

      - name: Install Google SDK
        shell: cmd
        run: |
          curl.exe -o gcloud-sdk.zip --url https://storage.googleapis.com/cloud-sdk-release/google-cloud-cli-502.0.0-windows-x86_64.zip
          tar -xf gcloud-sdk.zip          
          dir .
          .\google-cloud-sdk\install.bat --quiet
          dir D:\a\ds2-2025\ds2-2025\google-cloud-sdk\bin
          echo "D:\a\ds2-2025\ds2-2025\google-cloud-sdk\bin" >> $GITHUB_PATH

      - name: Check Google SDK
        shell: cmd
        run: |                 
          dir D:\a\ds2-2025\ds2-2025\google-cloud-sdk\bin
          D:\a\ds2-2025\ds2-2025\google-cloud-sdk\bin\gcloud info
          gcloud info

      - name: Setup Micromamba ${{ matrix.python-version }}
        uses: mamba-org/setup-micromamba@v2
        with:
          micromamba-version: '1.5.10-0'
          environment-name: ds2-tests
          environment-file: ${{ env.CONDA_ENV_FILE }}
          init-shell: bash
          cache-environment: true
          cache-environment-key: "${{runner.os}}-${{runner.arch}}-py${{matrix.python-version}}-${{env.TODAY}}-${{hashFiles(env.CONDA_ENV_FILE)}}"
          create-args: >-
            python=${{matrix.python-version}}

      - name: Version info
        run: |
          micromamba info
          micromamba list > $LOG_FILE

      - name: Save tests log as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Build-${{matrix.python-version}}-${{matrix.os}}
          path: ${{env.LOG_FILE}}
          retention-days: 90
